-- Baseline catalogo compartido por taller: marcas y modelos comunes en Colombia.
-- IDs son slugs legibles, no cuid -- validos igual: la columna es TEXT sin formato exigido.

INSERT INTO "marcas_vehiculo" ("id", "nombre") VALUES
('marca_toyota', 'Toyota'),
('marca_mazda', 'Mazda'),
('marca_chevrolet', 'Chevrolet'),
('marca_renault', 'Renault'),
('marca_nissan', 'Nissan'),
('marca_kia', 'Kia'),
('marca_hyundai', 'Hyundai'),
('marca_ford', 'Ford'),
('marca_honda', 'Honda'),
('marca_volkswagen', 'Volkswagen'),
('marca_suzuki', 'Suzuki'),
('marca_mitsubishi', 'Mitsubishi'),
('marca_peugeot', 'Peugeot'),
('marca_fiat', 'Fiat'),
('marca_bmw', 'BMW'),
('marca_mercedes_benz', 'Mercedes-Benz'),
('marca_audi', 'Audi'),
('marca_jeep', 'Jeep'),
('marca_subaru', 'Subaru'),
('marca_mini', 'Mini');

INSERT INTO "modelos_vehiculo" ("id", "marca_id", "nombre") VALUES
('modelo_toyota_corolla', 'marca_toyota', 'Corolla'),
('modelo_toyota_hilux', 'marca_toyota', 'Hilux'),
('modelo_toyota_rav4', 'marca_toyota', 'RAV4'),
('modelo_toyota_yaris', 'marca_toyota', 'Yaris'),
('modelo_toyota_prado', 'marca_toyota', 'Prado'),
('modelo_mazda_mazda_2', 'marca_mazda', 'Mazda 2'),
('modelo_mazda_mazda_3', 'marca_mazda', 'Mazda 3'),
('modelo_mazda_cx_5', 'marca_mazda', 'CX-5'),
('modelo_mazda_cx_30', 'marca_mazda', 'CX-30'),
('modelo_mazda_bt_50', 'marca_mazda', 'BT-50'),
('modelo_chevrolet_spark', 'marca_chevrolet', 'Spark'),
('modelo_chevrolet_sail', 'marca_chevrolet', 'Sail'),
('modelo_chevrolet_onix', 'marca_chevrolet', 'Onix'),
('modelo_chevrolet_tracker', 'marca_chevrolet', 'Tracker'),
('modelo_chevrolet_captiva', 'marca_chevrolet', 'Captiva'),
('modelo_renault_sandero', 'marca_renault', 'Sandero'),
('modelo_renault_logan', 'marca_renault', 'Logan'),
('modelo_renault_duster', 'marca_renault', 'Duster'),
('modelo_renault_kwid', 'marca_renault', 'Kwid'),
('modelo_renault_koleos', 'marca_renault', 'Koleos'),
('modelo_nissan_versa', 'marca_nissan', 'Versa'),
('modelo_nissan_sentra', 'marca_nissan', 'Sentra'),
('modelo_nissan_kicks', 'marca_nissan', 'Kicks'),
('modelo_nissan_x_trail', 'marca_nissan', 'X-Trail'),
('modelo_nissan_frontier', 'marca_nissan', 'Frontier'),
('modelo_kia_picanto', 'marca_kia', 'Picanto'),
('modelo_kia_rio', 'marca_kia', 'Rio'),
('modelo_kia_sportage', 'marca_kia', 'Sportage'),
('modelo_kia_cerato', 'marca_kia', 'Cerato'),
('modelo_kia_soluto', 'marca_kia', 'Soluto'),
('modelo_hyundai_accent', 'marca_hyundai', 'Accent'),
('modelo_hyundai_tucson', 'marca_hyundai', 'Tucson'),
('modelo_hyundai_santa_fe', 'marca_hyundai', 'Santa Fe'),
('modelo_hyundai_grand_i10', 'marca_hyundai', 'Grand i10'),
('modelo_hyundai_creta', 'marca_hyundai', 'Creta'),
('modelo_ford_fiesta', 'marca_ford', 'Fiesta'),
('modelo_ford_focus', 'marca_ford', 'Focus'),
('modelo_ford_explorer', 'marca_ford', 'Explorer'),
('modelo_ford_ranger', 'marca_ford', 'Ranger'),
('modelo_ford_ecosport', 'marca_ford', 'EcoSport'),
('modelo_honda_civic', 'marca_honda', 'Civic'),
('modelo_honda_cr_v', 'marca_honda', 'CR-V'),
('modelo_honda_hr_v', 'marca_honda', 'HR-V'),
('modelo_honda_fit', 'marca_honda', 'Fit'),
('modelo_honda_city', 'marca_honda', 'City'),
('modelo_volkswagen_gol', 'marca_volkswagen', 'Gol'),
('modelo_volkswagen_polo', 'marca_volkswagen', 'Polo'),
('modelo_volkswagen_jetta', 'marca_volkswagen', 'Jetta'),
('modelo_volkswagen_tiguan', 'marca_volkswagen', 'Tiguan'),
('modelo_volkswagen_amarok', 'marca_volkswagen', 'Amarok'),
('modelo_suzuki_swift', 'marca_suzuki', 'Swift'),
('modelo_suzuki_vitara', 'marca_suzuki', 'Vitara'),
('modelo_suzuki_alto', 'marca_suzuki', 'Alto'),
('modelo_suzuki_ertiga', 'marca_suzuki', 'Ertiga'),
('modelo_suzuki_grand_vitara', 'marca_suzuki', 'Grand Vitara'),
('modelo_mitsubishi_lancer', 'marca_mitsubishi', 'Lancer'),
('modelo_mitsubishi_outlander', 'marca_mitsubishi', 'Outlander'),
('modelo_mitsubishi_asx', 'marca_mitsubishi', 'ASX'),
('modelo_mitsubishi_l200', 'marca_mitsubishi', 'L200'),
('modelo_mitsubishi_montero', 'marca_mitsubishi', 'Montero'),
('modelo_peugeot_208', 'marca_peugeot', '208'),
('modelo_peugeot_3008', 'marca_peugeot', '3008'),
('modelo_peugeot_partner', 'marca_peugeot', 'Partner'),
('modelo_peugeot_2008', 'marca_peugeot', '2008'),
('modelo_peugeot_308', 'marca_peugeot', '308'),
('modelo_fiat_uno', 'marca_fiat', 'Uno'),
('modelo_fiat_mobi', 'marca_fiat', 'Mobi'),
('modelo_fiat_cronos', 'marca_fiat', 'Cronos'),
('modelo_fiat_palio', 'marca_fiat', 'Palio'),
('modelo_fiat_argo', 'marca_fiat', 'Argo'),
('modelo_bmw_serie_3', 'marca_bmw', 'Serie 3'),
('modelo_bmw_serie_5', 'marca_bmw', 'Serie 5'),
('modelo_bmw_x1', 'marca_bmw', 'X1'),
('modelo_bmw_x3', 'marca_bmw', 'X3'),
('modelo_bmw_x5', 'marca_bmw', 'X5'),
('modelo_mercedes_benz_clase_a', 'marca_mercedes_benz', 'Clase A'),
('modelo_mercedes_benz_clase_c', 'marca_mercedes_benz', 'Clase C'),
('modelo_mercedes_benz_gla', 'marca_mercedes_benz', 'GLA'),
('modelo_mercedes_benz_glc', 'marca_mercedes_benz', 'GLC'),
('modelo_mercedes_benz_sprinter', 'marca_mercedes_benz', 'Sprinter'),
('modelo_audi_a3', 'marca_audi', 'A3'),
('modelo_audi_a4', 'marca_audi', 'A4'),
('modelo_audi_q3', 'marca_audi', 'Q3'),
('modelo_audi_q5', 'marca_audi', 'Q5'),
('modelo_audi_a6', 'marca_audi', 'A6'),
('modelo_jeep_renegade', 'marca_jeep', 'Renegade'),
('modelo_jeep_compass', 'marca_jeep', 'Compass'),
('modelo_jeep_wrangler', 'marca_jeep', 'Wrangler'),
('modelo_jeep_grand_cherokee', 'marca_jeep', 'Grand Cherokee'),
('modelo_jeep_patriot', 'marca_jeep', 'Patriot'),
('modelo_subaru_forester', 'marca_subaru', 'Forester'),
('modelo_subaru_xv', 'marca_subaru', 'XV'),
('modelo_subaru_outback', 'marca_subaru', 'Outback'),
('modelo_subaru_impreza', 'marca_subaru', 'Impreza'),
('modelo_mini_cooper', 'marca_mini', 'Cooper'),
('modelo_mini_countryman', 'marca_mini', 'Countryman'),
('modelo_mini_clubman', 'marca_mini', 'Clubman');
